### ISSUE TITLE
[Bug] Pydantic's SecretStr type is not supported

### ISSUE THREAD

**Issue by konsilanto** [sanic-org/sanic-ext#186]
**Describe the bug**
Trying to return a pydantic model with an attribute `SecretStr` yields the following error:

```
Traceback (most recent call last):
  File "handle_request", line 96, in handle_request
  File "/tmp/test_sanic/.venv/lib/python3.10/site-packages/sanic_ext/extensions/openapi/openapi.py", line 232, in handler
    retval = await retval
  File "/tmp/test_sanic/.venv/lib/python3.10/site-packages/sanic_ext/extras/validation/decorator.py", line 75, in decorated_function
    retval = await retval
  File "/tmp/test_sanic/server.py", line 25, in user
    return json(body)
  File "/tmp/test_sanic/.venv/lib/python3.10/site-packages/sanic/response/convenience.py", line 50, in json
    return JSONResponse(
  File "/tmp/test_sanic/.venv/lib/python3.10/site-packages/sanic/response/types.py", line 248, in __init__
    self._encode_body(self._use_dumps(body, **self._use_dumps_kwargs)),
TypeError: User(username='string', password=SecretStr('**********')) is not JSON serializable
```

Maybe it is not intended to support this but I supposed that I get a representation containing `*` marks.
The [pydantic documentation](https://docs.pydantic.dev/usage/types/#secret-types) describes that it will be formatted using `*` on serializing to json.

If I uncomment the response part of the openapi decorator I get the following error message:

```
  ...
  File "/usr/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'unicode' is not defined
```

**To Reproduce**

```
from sanic import Sanic, json
from sanic_ext import openapi, validate

from pydantic import BaseModel, SecretStr

class User(BaseModel):
    username: str
    password: SecretStr

app = Sanic("MyHelloWorldApp")

@app.post("/user")
@openapi.definition(
    body={'application/json': User.schema()},
    # response=[
    #     openapi.definitions.Response(
    #         content={"application/json": User},
    #         description="...",
    #         status=200,
    #     )
    # ]
)
@validate(json=User)
async def user(request, body: User):
    return json(body)
```

**Expected behavior**
To get a json representation consisting '*' marks.

**Environment (please complete the following information):**
 - OS: Manjaro
 - Browser: firefox

**Comment by konsilanto** [comment]
I was able to partially fix the problem by changing the default function for dumping models to json by using the function `pydantic_encoder`:

```
from sanic import Sanic, json
from sanic_ext import openapi, validate

from pydantic import BaseModel, SecretStr

class User(BaseModel):
    username: str
    password: SecretStr


from json import dumps as json_dumps

from functools import partial
from pydantic.json import pydantic_encoder

dumps = partial(json_dumps, default=pydantic_encoder)

app = Sanic("MyHelloWorldApp",
            dumps=dumps)


@app.post("/user")
@openapi.definition(
    body={'application/json': User.schema()},
    # response=[
    #     openapi.definitions.Response(
    #         content={"application/json": User},
    #         description="...",
    #         status=200,
    #     )
    # ]
)
@validate(json=User)
async def user(request, body: User):
    return json(body)
```

This eliminates the `TypeError` but does not have any impact on the `NameError`.

BTW, I am using Sanic v22.12.0.

**Comment by ahopkins** [comment]
Looks like pydantic is doing some voodoo magic under the hood. Not sure how to address this yet.
